.TH "inc Directory Reference" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdbg\&.h\fP"
.br
.RI "\fIDebug basic functionality\&. \fP"
.ti -1c
.RI "file \fBinc/dbg_cfg\&.h\fP"
.br
.RI "\fIConfiguration of Debug\&. \fP"
.ti -1c
.RI "file \fBkernel\&.h\fP"
.br
.RI "\fIInterface of kernel\&. \fP"
.ti -1c
.RI "file \fBinc/kernel_cfg\&.h\fP"
.br
.RI "\fIConfiguration of Kernel\&. \fP"
.in -1c
