.TH "arch Directory Reference" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arch Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkcore\&.h\fP"
.br
.RI "\fIInterface of CPU port - Template\&. \fP"
.in -1c
