.TH "kernel Directory Reference" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkernel\&.h\fP"
.br
.RI "\fIMain kernel interface\&. \fP"
.ti -1c
.RI "file \fBsemaphore\&.h\fP"
.br
.RI "\fIInterface of semaphore\&. \fP"
.in -1c
