.TH "family Directory Reference" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
family Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBprofile\&.h\fP"
.br
.RI "\fIFamily port specific configuration options\&. \fP"
.in -1c
