.TH "generic Directory Reference" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generic Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBport\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtemplate/generic/dbg_cfg\&.h\fP"
.br
.RI "\fIConfiguration of Debug\&. \fP"
.ti -1c
.RI "file \fBtemplate/generic/kernel_cfg\&.h\fP"
.br
.RI "\fIConfiguration of Kernel - Template\&. \fP"
.in -1c
