.TH "generic Directory Reference" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generic Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB_port_\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkernel_cfg\&.h\fP"
.br
.RI "\fIConfiguration of Kernel - Template\&. \fP"
.in -1c
