.TH "bitop.h" 3 "Sat Nov 23 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bitop.h \- 
.PP
General purpose bit operations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'arch/cpu\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBES_BIT_DIMENSION\fP(array)   (sizeof(array) / sizeof(array[0]))"
.br
.RI "\fIDetermines the first dimension of an array\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_DIV_ROUND\fP(numerator, denominator)   (((numerator) + ((denominator) / 2U)) / (denominator))"
.br
.RI "\fIRound a division\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_DIV_ROUNDUP\fP(numerator, denominator)   (((numerator) + (denominator) - 1u) / (denominator))"
.br
.RI "\fIRound up a division\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_MAX\fP(expr1, expr2)   ((expr1 > expr2) ? expr1 : expr2))"
.br
.RI "\fIVraca vecu vrednost od ponudjenih vrednosti \fIexpr1\fP i \fIexpr2\fP\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_MIN\fP(expr1, expr2)   ((expr1 < expr2) ? expr1 : expr2))"
.br
.RI "\fIVraca manju vrednost od ponudjenih vrednosti \fIexpr1\fP i \fIexpr2\fP\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_ALIGN\fP(num, align)   ((num) & ~((align) - 1u))"
.br
.RI "\fIVrsi poravnjanje \fInum\fP promenjive sa granicama specificarane u \fIalign\fP\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_ALIGN_UP\fP(num, align)   (((num) + (align) - 1u) & ~((align) - 1u))"
.br
.RI "\fIVrsi poravnjanje \fInum\fP promenjive sa granicama specificarane u \fIalign\fP\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_FIND_LAST_SET\fP(val)   \fBPORT_BIT_FIND_LAST_SET\fP(val)"
.br
.RI "\fIFind last set bit in a word\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_BIT_PWR2\fP(pwr)   \fBPORT_BIT_PWR2\fP(pwr)"
.br
.RI "\fIHelper macro: calculate 2^pwr expression\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_IS_POW2\fP(num)   (!((num) & ((num) - 1)))"
.br
.RI "\fIDa li je \fCexpr\fP jednak nekom stepenu dvojke? \fP"
.ti -1c
.RI "#define \fBES_BIT_UINT8_LOG2\fP(x)"
.br
.RI "\fICalculate log2 for value \fCx\fP during the compilation\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_MASK_MSB\fP(type)   (1uL << ((sizeof(type) * 8u) - 1u))"
.br
.RI "\fIKreira masku za MSB bit koji odgovara tipu \fCtype\fP\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_SET_MSB\fP(var)"
.br
.RI "\fIPostavlja MSB bit na jedan, '1'\&. \fP"
.ti -1c
.RI "#define \fBES_BIT_CLR_MSB\fP(var)"
.br
.RI "\fIPostavlja MSB bit na nulu, '0'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
General purpose bit operations\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
