.TH "changelog" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
changelog \- Change Log 
Brief change log
.PP
2013-07-03 Nenad Radulovic
.PP
.IP "\(bu" 2
\fCNEW:\fP Initial implementation of system timer
.IP "\(bu" 2
\fCNEW:\fP Initial implementation of power savings features
.IP "\(bu" 2
\fCUPDATE:\fP Many functions have full API contract restrictions
.PP
.PP
2013-05-28 Nenad Radulovic
.PP
.IP "\(bu" 2
\fCNEW:\fP Initial project import
.IP "\(bu" 2
\fCNEW:\fP Initial commit
.IP "\(bu" 2
\fCUPDATE:\fP Eclipse project files are added to gitignore 
.PP

