.TH "cpu.h" 3 "Sat Nov 23 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpu.h \- 
.PP
Interface of CPU port - Template\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'arch/compiler\&.h'\fP
.br
\fC#include 'arch/cpu_cfg\&.h'\fP
.br
\fC#include 'kernel_cfg\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBportStck\fP"
.br
.RI "\fIStack structure used for stack declaration in order to force the alignment Alignment of stack structure\&. \fP"
.ti -1c
.RI "struct \fBportCtx\fP"
.br
.RI "\fIPort context structure\&. \fP"
.in -1c
.SS "Macros"

.PP
.RI "\fBPort constants\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBPORT_DEF_DATA_WIDTH\fP   8u"
.br
.RI "\fIThis macro specifies the bit width of atomic data type portReg_T\&. \fP"
.ti -1c
.RI "#define \fBPORT_DEF_DATA_ALIGNMENT\fP   1u"
.br
.RI "\fIDefines required data alignment in bytes\&. \fP"
.ti -1c
.RI "#define \fBPORT_DEF_MAX_ISR_PRIO\fP   (\fBPORT_CFG_MAX_ISR_PRIO\fP)"
.br
.RI "\fIDefines maximum interrupt priority which can use kernel services\&. \fP"
.ti -1c
.RI "#define \fBPORT_DEF_STCK_MINSIZE\fP   (sizeof(struct \fBportCtx\fP) / sizeof(\fBportReg_T\fP))"
.br
.RI "\fIThis macro specifies the minimal size of the thread stack\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBSystem timer constants\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBPORT_DEF_SYSTMR_ONE_TICK\fP   (CFG_SYSTMR_CLOCK_FREQUENCY / \fBCFG_SYSTMR_EVENT_FREQUENCY\fP)"
.br
.RI "\fISystem timer reload value for one tick\&. \fP"
.ti -1c
.RI "#define \fBPORT_DEF_SYSTMR_MAX_TICKS\fP   (\fBCPU_DEF_SYSTMR_MAX_VAL\fP / \fBPORT_DEF_SYSTMR_ONE_TICK\fP)"
.br
.RI "\fIMaximum number of ticks without overflowing the system timer\&. \fP"
.ti -1c
.RI "#define \fBPORT_DEF_SYSTMR_WAKEUP_TH_VAL\fP   600u"
.br
.RI "\fIThreshold system timer value for new tick\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBKernel threads port dependent settings\fP"
.br
Kernel uses several threads for system management\&. This section defines port dependent settings for the threads\&. 
.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBPORT_DEF_KVTMR_STCK_SIZE\fP   40u"
.br
.RI "\fIKernel Virtual Timer Thread stack size\&. \fP"
.ti -1c
.RI "#define \fBPORT_DEF_KIDLE_STCK_SIZE\fP   40u"
.br
.RI "\fIKernel Idle Thread stack size\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBInterrupt management\fP"
.br
PORT_ISR_\&.\&.\&. macros are used by esKernIsrEnter() and esKernIsrExit() functions\&. They are used to keep the current level of ISR nesting\&. Scheduler should be invoked only from the last ISR that is executing\&. 
.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBPORT_INT_ENABLE\fP()"
.br
.RI "\fIGlobal Enable interrupt sources\&. \fP"
.ti -1c
.RI "#define \fBPORT_INT_DISABLE\fP()"
.br
.RI "\fIGlobal Disable all interrupt sources\&. \fP"
.ti -1c
.RI "#define \fBPORT_INT_PRIO_SET\fP(prio)"
.br
.RI "\fISet interrupt priority mask\&. \fP"
.ti -1c
.RI "#define \fBPORT_INT_PRIO_GET\fP(prio)"
.br
.RI "\fIGet current interrupt priority mask\&. \fP"
.ti -1c
.RI "#define \fBPORT_INT_PRIO_REPLACE\fP(oldPrio, newPrio)"
.br
.RI "\fIGet current and set new interrupt priority mask\&. \fP"
.ti -1c
.RI "#define \fBPORT_ISR_ENTER\fP()"
.br
.RI "\fIEnter ISR\&. Increment PortIsrNesting variable to keep track of ISR nesting\&. \fP"
.ti -1c
.RI "#define \fBPORT_ISR_EXIT\fP()"
.br
.RI "\fIExit ISR\&. Decrement PortIsrNesting variable to keep track of ISR nesting\&. \fP"
.ti -1c
.RI "#define \fBPORT_ISR_IS_LAST\fP()   (0u == PortIsrNesting ? TRUE : FALSE)"
.br
.RI "\fIIf isrNesting variable is zero then the last ISR is executing and scheduler should be invoked\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBSystem timer management\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBPORT_SYSTMR_INIT\fP(val)"
.br
.RI "\fIInitialize system timer and associated interrupt\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_TERM\fP()"
.br
.RI "\fIStop the timer if it is running and disable associated interrupt\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_GET_RVAL\fP()"
.br
.RI "\fIGet system timer reload value\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_GET_CVAL\fP()"
.br
.RI "\fIGet system timer current value\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_RLD\fP(val)"
.br
.RI "\fIReload the system timer with specified number\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_ENABLE\fP()"
.br
.RI "\fIEnable the system timer\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_DISABLE\fP()"
.br
.RI "\fIDisable the system timer\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_ISR_ENABLE\fP()"
.br
.RI "\fIEnable the system timer interrupt\&. \fP"
.ti -1c
.RI "#define \fBPORT_SYSTMR_ISR_DISABLE\fP()"
.br
.RI "\fIDisable the system timer interrupt\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBScheduler bit operations support\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBPORT_BIT_FIND_LAST_SET\fP(val)   \fBportFindLastSet\fP(val)"
.br
.RI "\fIFind last set bit in a word\&. \fP"
.ti -1c
.RI "#define \fBPORT_BIT_PWR2\fP(pwr)   (1U << (pwr))"
.br
.RI "\fIHelper macro: calculate 2^pwr expression\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBGeneral port macros\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBPORT_INIT_EARLY\fP()"
.br
.RI "\fIEarly port initialization\&. \fP"
.ti -1c
.RI "#define \fBPORT_INIT\fP()"
.br
.RI "\fIPort initialization\&. \fP"
.ti -1c
.RI "#define \fBPORT_INIT_LATE\fP()"
.br
.RI "\fILate port initialization\&. \fP"
.ti -1c
.RI "#define \fBPORT_TERM\fP()"
.br
.RI "\fITerminate port\&. \fP"
.ti -1c
.RI "#define \fBPORT_STCK_SIZE\fP(size)"
.br
.RI "\fICalculate the stack size\&. \fP"
.ti -1c
.RI "#define \fBPORT_CRITICAL_EXIT_SLEEP\fP()   portIntSetSleepEnter_(intStatus_)"
.br
.RI "\fIExit critical section and enter sleep state\&. \fP"
.in -1c
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBportReg_T\fP"
.br
.RI "\fIData type which corresponds to the general purpose register\&. \fP"
.ti -1c
.RI "typedef struct \fBportStck\fP \fBportStck_T\fP"
.br
.RI "\fIStack type\&. \fP"
.in -1c
.SS "Functions"

.PP
.RI "\fBScheduler support\fP"
.br

.PP
\fBNote:\fP
.RS 4
These functions are extensively used by the scheduler and therefore they should be optimized for the architecture being used\&. 
.RE
.PP

.PP
.in +1c
.in +1c
.ti -1c
.RI "uint_fast8_t \fBportFindLastSet\fP (\fBportReg_T\fP val)"
.br
.RI "\fIFind last set bit in a word\&. \fP"
.in -1c
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBportReg_T\fP \fBPortIsrNesting\fP"
.br
.RI "\fIVariable to keep track of ISR nesting\&. \fP"
.ti -1c
.RI "const PORT_C_ROM \fBportReg_T\fP \fBPwr2LKP\fP [\fBPORT_DEF_DATA_WIDTH\fP]"
.br
.RI "\fILook up table for: 2^n expression\&. \fP"
.in -1c
.SS "Dispatcher context switching"

.in +1c
.ti -1c
.RI "#define \fBPORT_CTX_INIT\fP(stck, stackSize, thread, arg)"
.br
.RI "\fIInitialize the thread context\&. \fP"
.ti -1c
.RI "#define \fBPORT_CTX_SW\fP()"
.br
.RI "\fIDo the context switch - invoked from API level\&. \fP"
.ti -1c
.RI "#define \fBPORT_CTX_SW_ISR\fP()"
.br
.RI "\fIDo the context switch - invoked from ISR level\&. \fP"
.ti -1c
.RI "#define \fBPORT_CTX_SW_START\fP()"
.br
.RI "\fIStart the first thread\&. \fP"
.ti -1c
.RI "void * \fBportCtxInit\fP (void *stck, size_t stckSize, void(*fn)(void *), void *arg)"
.br
.RI "\fIInitialize the thread context\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface of CPU port - Template\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
