.TH "cpu_cfg.h" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpu_cfg.h \- 
.PP
Configuration of CPU port - Template\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.PP
.RI "\fBPort General configuration\fP"
.br
Configuration options and settings which are available for every port\&.
.PP
\fBNote:\fP
.RS 4
1) All port General configuration macros are prefixed with \fCCFG_\fP string\&. 
.PP
2) All port specific options and constants are prefixed with \fCCPU_\fP string\&. 
.RE
.PP

.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBCFG_CRITICAL_PRIO\fP   1U"
.br
.RI "\fIPriority of critical sections in kernel\&. \fP"
.ti -1c
.RI "#define \fBCFG_SYSTMR_CLOCK_FREQUENCY\fP   1000000UL"
.br
.RI "\fIThe frequency of clock which is used for the system timer\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Configuration of CPU port - Template\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
