.TH "dbg.c" 3 "Sat Nov 23 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbg.c \- 
.PP
Implementation of Debug module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'arch/compiler\&.h'\fP
.br
\fC#include 'arch/cpu\&.h'\fP
.br
\fC#include 'kernel/dbg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "PORT_C_NORETURN void \fBdbgAssert\fP (const PORT_C_ROM struct \fBdbgCobj_\fP *cObj, const PORT_C_ROM char *expr, enum \fBesDbgMsgNum\fP msg)"
.br
.RI "\fIAn assertion has failed\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const PORT_C_ROM char 
.br
*const PORT_C_ROM_VAR \fBDbgMsg\fP []"
.br
.RI "\fIDefinition text of debug messages\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of Debug module\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
