.TH "dbg_cfg.h" 3 "Sat Nov 23 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbg_cfg.h \- 
.PP
Configuration of Debug\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCFG_DBG_ENABLE\fP   1U"
.br
.RI "\fIEnable/disable Debug module\&. \fP"
.ti -1c
.RI "#define \fBCFG_DBG_API_VALIDATION\fP   1U"
.br
.RI "\fIEnable/disable API arguments validation\&. \fP"
.ti -1c
.RI "#define \fBCFG_DBG_INTERNAL_CHECK\fP   1U"
.br
.RI "\fIEnable/disable internal checks\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Configuration of Debug\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
