.TH "Configuration" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration \- 
.PP
Debug configuration options\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCFG_DBG_ENABLE\fP   1"
.br
.RI "\fIEnable/disable Debug module\&. \fP"
.ti -1c
.RI "#define \fBCFG_DBG_API_VALIDATION\fP   1"
.br
.RI "\fIEnable/disable API arguments validation\&. \fP"
.ti -1c
.RI "#define \fBCFG_DBG_INTERNAL_CHECK\fP   1"
.br
.RI "\fIEnable/disable internal checks\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Debug configuration options\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CFG_DBG_ENABLE   1"

.PP
Enable/disable Debug module\&. Possible values:
.IP "\(bu" 2
0 - All debug options are disabled
.IP "\(bu" 2
1 - Debug options can be enabled individually 
.PP

.SS "#define CFG_DBG_API_VALIDATION   1"

.PP
Enable/disable API arguments validation\&. Possible values:
.IP "\(bu" 2
0 - API validation is disabled
.IP "\(bu" 2
1 - API validation is enabled 
.PP
\fBNote:\fP
.RS 4
This option is enabled only if \fBCFG_DBG_ENABLE\fP is enabled, too\&. 
.RE
.PP

.PP

.SS "#define CFG_DBG_INTERNAL_CHECK   1"

.PP
Enable/disable internal checks\&. Possible values:
.IP "\(bu" 2
0 - API validation is disabled
.IP "\(bu" 2
1 - API validation is enabled 
.PP
\fBNote:\fP
.RS 4
This option is enabled only if \fBCFG_DBG_ENABLE\fP is enabled, too\&. 
.RE
.PP

.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
