.TH "Internals" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Internals \- 
.PP
Debug inner work\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "PORT_C_NORETURN void \fBdbgAssert\fP (const PORT_C_ROM struct \fBdbgCobj\fP *cObj, const PORT_C_ROM char *expr, enum \fBesDbgMsg\fP msg)"
.br
.RI "\fIAn assertion has failed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Debug inner work\&. 


.SH "Function Documentation"
.PP 
.SS "PORT_C_NORETURN void dbgAssert (const PORT_C_ROM struct \fBdbgCobj\fP *cObj, const PORT_C_ROM char *expr, enum \fBesDbgMsg\fPmsg)"

.PP
An assertion has failed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcObj\fP C Object describes where the error occured\&. 
.br
\fIexpr\fP Expression: is pointer to the string containing the expression that failed to evaluate to \fCTRUE\fP\&. 
.br
\fImsg\fP Message: is enum esDbgMsg containing some information about the error\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
1) \fCNULL != cObj\fP 
.PP
2) \fCNULL != expr\fP 
.RE
.PP
\fBNote:\fP
.RS 4
1) This function is called only if \fBCFG_DBG_API_VALIDATION\fP is active\&.
.RE
.PP
Function will just print the information which was given by the macros\&. 
.PP
\fBObject class:\fP
.RS 4
\fBNot API\fP object, this object is not part of the application programming interface and it is intended for internal use only\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
