.TH "dbgModInfo" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbgModInfo \- 
.PP
Debug module information structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dbg\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const PORT_C_ROM char *const 
.br
PORT_C_ROM_VAR \fBname\fP"
.br
.ti -1c
.RI "const PORT_C_ROM char *const 
.br
PORT_C_ROM_VAR \fBdesc\fP"
.br
.ti -1c
.RI "const PORT_C_ROM char *const 
.br
PORT_C_ROM_VAR \fBauth\fP"
.br
.ti -1c
.RI "const PORT_C_ROM char *const 
.br
PORT_C_ROM_VAR \fBfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Debug module information structure\&. 


.PP
\fBObject class:\fP
.RS 4
\fBNot API\fP object, this object is not part of the application programming interface and it is intended for internal use only\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
