.TH "esThdQ::prioBM" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esThdQ::prioBM \- 
.PP
Priority Bit Map structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBportReg_T\fP \fBbitGrp\fP"
.br
.RI "\fIBit group indicator\&. \fP"
.ti -1c
.RI "\fBportReg_T\fP \fBbit\fP [\fBPRIO_BM_GRP_INDX\fP]"
.br
.RI "\fIBit priority indicator\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Priority Bit Map structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBportReg_T\fP esThdQ::prioBM::bitGrp"

.PP
Bit group indicator\&. 
.SS "\fBportReg_T\fP esThdQ::prioBM::bit[\fBPRIO_BM_GRP_INDX\fP]"

.PP
Bit priority indicator\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
