.TH "esThd" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esThd \- 
.PP
Thread structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernel\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBthdL_\fP"
.br
.RI "\fIThread linked List structure\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBportStck_T\fP * \fBstck\fP"
.br
.RI "\fIPointer to thread's Top Of Stack\&. \fP"
.ti -1c
.RI "struct \fBesThd::thdL_\fP \fBthdL\fP"
.br
.RI "\fIThread linked list\&. \fP"
.ti -1c
.RI "uint_fast8_t \fBprio\fP"
.br
.RI "\fIThread priority level\&. \fP"
.ti -1c
.RI "uint_fast8_t \fBiprio\fP"
.br
.RI "\fIInitial Thread Priority level\&. \fP"
.ti -1c
.RI "uint_fast8_t \fBqCnt\fP"
.br
.RI "\fIQuantum counter\&. \fP"
.ti -1c
.RI "uint_fast8_t \fBqRld\fP"
.br
.RI "\fIQuantum counter reload value\&. \fP"
.ti -1c
.RI "portReg_T \fBsignature\fP"
.br
.RI "\fIThread structure signature\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Thread structure\&. 

A thread structure is a data structure used by kernel to maintain information about a thread\&. Each thread requires its own ID structure and the structure is allocated in user memory space (RAM)\&. The address of the thread’s ID structure is provided to OS thread-related services\&.
.PP
Thread structure is used as thread ID and a thread is always referenced using this structure\&. 
.PP
\fBObject class:\fP
.RS 4
Regular \fBAPI\fP object, this object is part of the application programming interface\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "\fBportStck_T\fP* esThd::stck"

.PP
Pointer to thread's Top Of Stack\&. 
.SS "struct \fBesThd::thdL_\fP                esThd::thdL"

.PP
Thread linked list\&. 
.SS "uint_fast8_t esThd::prio"

.PP
Thread priority level\&. 
.SS "uint_fast8_t esThd::iprio"

.PP
Initial Thread Priority level\&. 
.SS "uint_fast8_t esThd::qCnt"

.PP
Quantum counter\&. 
.SS "uint_fast8_t esThd::qRld"

.PP
Quantum counter reload value\&. 
.SS "portReg_T esThd::signature"

.PP
Thread structure signature\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
