.TH "esThdQ" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esThdQ \- 
.PP
Thread Queue structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernel\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBprioBM\fP"
.br
.RI "\fIPriority Bit Map structure\&. \fP"
.ti -1c
.RI "struct \fBthdLSentinel\fP"
.br
.RI "\fIThread linked list sentinel structure\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBesThdQ::prioBM\fP \fBprioOcc\fP"
.br
.RI "\fIPriority Occupancy\&. \fP"
.ti -1c
.RI "struct \fBesThdQ::thdLSentinel\fP \fBgrp\fP [\fBCFG_SCHED_PRIO_LVL\fP]"
.br
.RI "\fIArray of thread linked list sentinel structures\&. \fP"
.ti -1c
.RI "\fBportReg_T\fP \fBsignature\fP"
.br
.RI "\fIThread Queue struct signature, see \fBDebug: Error checking\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Thread Queue structure\&. 


.PP
\fBObject class:\fP
.RS 4
Regular \fBAPI\fP object, this object is part of the application programming interface\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "struct \fBesThdQ::prioBM\fP                esThdQ::prioOcc"

.PP
Priority Occupancy\&. 
.SS "struct \fBesThdQ::thdLSentinel\fP                esThdQ::grp[\fBCFG_SCHED_PRIO_LVL\fP]"

.PP
Array of thread linked list sentinel structures\&. 
.SS "\fBportReg_T\fP esThdQ::signature"

.PP
Thread Queue struct signature, see \fBDebug: Error checking\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
