.TH "esThdQ::thdLSent_" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esThdQ::thdLSent_ \- 
.PP
Thread linked list sentinel structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBesThd\fP * \fBhead\fP"
.br
.RI "\fIPoints to the first thread in linked list\&. \fP"
.ti -1c
.RI "struct \fBesThd\fP * \fBnext\fP"
.br
.RI "\fIPoints to the next thread in linked list\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Thread linked list sentinel structure\&. 


.PP
\fBObject class:\fP
.RS 4
\fBNot API\fP object, this object is not part of the application programming interface and it is intended for internal use only\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "struct \fBesThd\fP* esThdQ::thdLSent_::head"

.PP
Points to the first thread in linked list\&. 
.SS "struct \fBesThd\fP* esThdQ::thdLSent_::next"

.PP
Points to the next thread in linked list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
