.TH "esVTmr::tmrL_" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esVTmr::tmrL_ \- 
.PP
Virtual Timer linked list structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBesVTmr\fP * \fBq\fP"
.br
.RI "\fIPoints to parent timer queue\&. \fP"
.ti -1c
.RI "struct \fBesVTmr\fP * \fBnext\fP"
.br
.RI "\fINext thread in Virtual Timer linked list\&. \fP"
.ti -1c
.RI "struct \fBesVTmr\fP * \fBprev\fP"
.br
.RI "\fIPrevious thread in virtual timer linked list\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Virtual Timer linked list structure\&. 


.PP
\fBObject class:\fP
.RS 4
\fBNot API\fP object, this object is not part of the application programming interface and it is intended for internal use only\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "struct \fBesVTmr\fP* esVTmr::tmrL_::q"

.PP
Points to parent timer queue\&. 
.SS "struct \fBesVTmr\fP* esVTmr::tmrL_::next"

.PP
Next thread in Virtual Timer linked list\&. 
.SS "struct \fBesVTmr\fP* esVTmr::tmrL_::prev"

.PP
Previous thread in virtual timer linked list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
