.TH "esVTmr::tmrL" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esVTmr::tmrL \- 
.PP
Virtual Timer linked list structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernel\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBesVTmr\fP * \fBq\fP"
.br
.RI "\fIPoints to parent timer list\&. \fP"
.ti -1c
.RI "struct \fBesVTmr\fP * \fBnext\fP"
.br
.RI "\fINext thread in Virtual Timer linked list\&. \fP"
.ti -1c
.RI "struct \fBesVTmr\fP * \fBprev\fP"
.br
.RI "\fIPrevious thread in virtual timer linked list\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Virtual Timer linked list structure\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBesVTmr\fP* esVTmr::tmrL::q"

.PP
Points to parent timer list\&. 
.SS "struct \fBesVTmr\fP* esVTmr::tmrL::next"

.PP
Next thread in Virtual Timer linked list\&. 
.SS "struct \fBesVTmr\fP* esVTmr::tmrL::prev"

.PP
Previous thread in virtual timer linked list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
