.TH "esVTmr" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esVTmr \- 
.PP
Virtual Timer structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kernel\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtmrL\fP"
.br
.RI "\fIVirtual Timer linked list structure\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBesVTmr::tmrL\fP \fBtmrL\fP"
.br
.RI "\fIVirtual Timer linked List\&. \fP"
.ti -1c
.RI "\fBesTick_T\fP \fBrtick\fP"
.br
.RI "\fIRelative tick value\&. \fP"
.ti -1c
.RI "void(* \fBfn\fP )(void *)"
.br
.RI "\fICallback function pointer\&. \fP"
.ti -1c
.RI "void * \fBarg\fP"
.br
.RI "\fICallback function argument\&. \fP"
.ti -1c
.RI "\fBportReg_T\fP \fBsignature\fP"
.br
.RI "\fITimer structure signature, see \fBDebug: Error checking\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Virtual Timer structure\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBesVTmr::tmrL\fP                \fBesVTmr::tmrL\fP"

.PP
Virtual Timer linked List\&. 
.SS "\fBesTick_T\fP esVTmr::rtick"

.PP
Relative tick value\&. 
.SS "void(*  esVTmr::fn)(void *)"

.PP
Callback function pointer\&. 
.SS "void* esVTmr::arg"

.PP
Callback function argument\&. 
.SS "\fBportReg_T\fP esVTmr::signature"

.PP
Timer structure signature, see \fBDebug: Error checking\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
