.TH "kcore.c" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kcore.c \- 
.PP
Implementation of CPU port - Template\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'kernel/kernel\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBportCtxInit\fP (void *stck, size_t stckSize, void(*fn)(void *), void *arg)"
.br
.RI "\fIInitialize the thread context\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of CPU port - Template\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
