.TH "kernel_cfg.h" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel_cfg.h \- 
.PP
Configuration of Kernel - Template\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.PP
.RI "\fBKernel configuration options and settings\fP"
.br
Kernel default configuration 
.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBCFG_SCHED_PRIO_LVL\fP   8U"
.br
.RI "\fIScheduler priority levels\&. \fP"
.ti -1c
.RI "#define \fBCFG_SCHED_TIME_QUANTUM\fP   10U"
.br
.RI "\fIScheduler Round-Robin time quantum\&. \fP"
.ti -1c
.RI "#define \fBCFG_SCHED_POWER_SAVE\fP   0U"
.br
.RI "\fIEnable/disable scheduler power savings mode\&. \fP"
.ti -1c
.RI "#define \fBCFG_SYSTMR_ADAPTIVE_MODE\fP   0U"
.br
.RI "\fISystem timer mode\&. \fP"
.ti -1c
.RI "#define \fBCFG_SYSTMR_EVENT_FREQUENCY\fP   100UL"
.br
.RI "\fIThe frequency of system tick event\&. \fP"
.ti -1c
.RI "#define \fBCFG_SYSTMR_TICK_TYPE\fP   2U"
.br
.RI "\fIThe size of the system timer counter\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBKernel hooks\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_SYSTMR_EVENT\fP   0U"
.br
.RI "\fISystem timer event hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_KERN_INIT\fP   0U"
.br
.RI "\fIPre kernel initialization hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_POST_KERN_INIT\fP   0U"
.br
.RI "\fIPost kernel initialization hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_KERN_START\fP   0U"
.br
.RI "\fIPre kernel start hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_POST_THD_INIT\fP   0U"
.br
.RI "\fIPost thread initialization hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_THD_TERM\fP   0U"
.br
.RI "\fIPre thread termination hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_IDLE\fP   0U"
.br
.RI "\fIPre idle hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_POST_IDLE\fP   0U"
.br
.RI "\fIPost idle hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_CTX_SW\fP   0U"
.br
.RI "\fIPre context switch hook function\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Configuration of Kernel - Template\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
