.TH "Configuration" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration \- 
.PP
Kernel Configuration settings\&.  

.SS "Kernel configuration options and settings"

.in +1c
.ti -1c
.RI "#define \fBCFG_SCHED_PRIO_LVL\fP   8u"
.br
.RI "\fIScheduler priority levels\&. \fP"
.ti -1c
.RI "#define \fBCFG_SCHED_TIME_QUANTUM\fP   10u"
.br
.RI "\fIScheduler Round-Robin time quantum\&. \fP"
.ti -1c
.RI "#define \fBCFG_SCHED_POWER_SAVE\fP   0u"
.br
.RI "\fIEnable/disable scheduler power savings mode\&. \fP"
.ti -1c
.RI "#define \fBCFG_SYSTMR_ADAPTIVE_MODE\fP   0u"
.br
.RI "\fISystem timer adaptive mode\&. \fP"
.ti -1c
.RI "#define \fBCFG_SYSTMR_EVENT_FREQUENCY\fP   100ul"
.br
.RI "\fIThe frequency of system timer tick event\&. \fP"
.ti -1c
.RI "#define \fBCFG_SYSTMR_TICK_TYPE\fP   2u"
.br
.RI "\fIThe size of the system timer tick event counter\&. \fP"
.in -1c
.SS "Kernel pre hooks"

.in +1c
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_SYSTMR_EVENT\fP   0u"
.br
.RI "\fISystem timer event hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_KERN_INIT\fP   0u"
.br
.RI "\fIPre kernel initialization hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_POST_KERN_INIT\fP   0u"
.br
.RI "\fIPost kernel initialization hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_KERN_START\fP   0u"
.br
.RI "\fIPre kernel start hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_POST_THD_INIT\fP   0u"
.br
.RI "\fIPost thread initialization hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_THD_TERM\fP   0u"
.br
.RI "\fIPre thread termination hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_IDLE\fP   0u"
.br
.RI "\fIPre idle hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_POST_IDLE\fP   0u"
.br
.RI "\fIPost idle hook function\&. \fP"
.ti -1c
.RI "#define \fBCFG_HOOK_PRE_CTX_SW\fP   0u"
.br
.RI "\fIPre context switch hook function\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Kernel Configuration settings\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CFG_SCHED_PRIO_LVL   8u"

.PP
Scheduler priority levels\&. Possible values:
.IP "\(bu" 2
Min: 3 (three priority levels)
.IP "\(bu" 2
Max: 256 
.PP

.SS "#define CFG_SCHED_TIME_QUANTUM   10u"

.PP
Scheduler Round-Robin time quantum\&. 
.SS "#define CFG_SCHED_POWER_SAVE   0u"

.PP
Enable/disable scheduler power savings mode\&. Possible values are:
.IP "\(bu" 2
0u - power saving is disabled
.IP "\(bu" 2
1u - power saving is enabled 
.PP

.SS "#define CFG_SYSTMR_ADAPTIVE_MODE   0u"

.PP
System timer adaptive mode\&. Possible values are:
.IP "\(bu" 2
0u - adaptive mode is disabled
.IP "\(bu" 2
1u - adaptive mode is enabled 
.PP

.SS "#define CFG_SYSTMR_EVENT_FREQUENCY   100ul"

.PP
The frequency of system timer tick event\&. 
.PP
\fBNote:\fP
.RS 4
This setting is valid only if configuration option \fBCFG_SYSTMR_CLOCK_FREQUENCY\fP is properly set in port configuration file \fBcpu_cfg\&.h\fP 
.RE
.PP

.SS "#define CFG_SYSTMR_TICK_TYPE   2u"

.PP
The size of the system timer tick event counter\&. Possible values are:
.IP "\(bu" 2
0u - 8 bit counter
.IP "\(bu" 2
1u - 16 bit counter
.IP "\(bu" 2
2u - 32 bit counter 
.PP

.SS "#define CFG_HOOK_PRE_SYSTMR_EVENT   0u"

.PP
System timer event hook function\&. 
.SS "#define CFG_HOOK_PRE_KERN_INIT   0u"

.PP
Pre kernel initialization hook function\&. 
.SS "#define CFG_HOOK_POST_KERN_INIT   0u"

.PP
Post kernel initialization hook function\&. 
.SS "#define CFG_HOOK_PRE_KERN_START   0u"

.PP
Pre kernel start hook function\&. 
.SS "#define CFG_HOOK_POST_THD_INIT   0u"

.PP
Post thread initialization hook function\&. 
.SS "#define CFG_HOOK_PRE_THD_TERM   0u"

.PP
Pre thread termination hook function\&. 
.SS "#define CFG_HOOK_PRE_IDLE   0u"

.PP
Pre idle hook function\&. 
.SS "#define CFG_HOOK_POST_IDLE   0u"

.PP
Post idle hook function\&. 
.SS "#define CFG_HOOK_PRE_CTX_SW   0u"

.PP
Pre context switch hook function\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
