.TH "Synchronization services" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Synchronization services \- 
.PP
Basic synchronization services\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBKernel lock\fP"
.br
.RI "\fIKernel locking\&. \fP"
.ti -1c
.RI "\fBSemaphore\fP"
.br
.RI "\fICounting semaphore\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Basic synchronization services\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
