.TH "Kernel" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel \- 
.PP
Overview\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConfiguration\fP"
.br
.RI "\fIKernel Configuration settings\&. \fP"
.ti -1c
.RI "\fBInterface\fP"
.br
.RI "\fIKernel main interface\&. \fP"
.ti -1c
.RI "\fBInternals\fP"
.br
.RI "\fIImplementation of kernel port independent code\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Overview\&. 

This documentation is divided into three subcategories:
.IP "\(bu" 2
Interface
.IP "\(bu" 2
Internals
.IP "\(bu" 2
Configuration 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
