.TH "Interface" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interface \- 
.PP
Kernel main interface\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGeneral kernel functions\fP"
.br
.RI "\fIKernel initialization, start-up, ISR management\&. \fP"
.ti -1c
.RI "\fBKernel control block\fP"
.br
.RI "\fILow-level kernel information and status access\&. \fP"
.ti -1c
.RI "\fBKernel hook functions\fP"
.br
.RI "\fIUser defined hook (callback) function prototypes\&. \fP"
.ti -1c
.RI "\fBKernel identification\fP"
.br
.RI "\fIKernel unique identification and current version number\&. \fP"
.ti -1c
.RI "\fBKernel lock\fP"
.br
.RI "\fIKernel lock management\&. \fP"
.ti -1c
.RI "\fBKernel time\fP"
.br
.RI "\fIKernel time management\&. \fP"
.ti -1c
.RI "\fBScheduler notification and invocation\fP"
.br
.RI "\fILow-level scheduler services\&. \fP"
.ti -1c
.RI "\fBThread\fP"
.br
.RI "\fIThread management services\&. \fP"
.ti -1c
.RI "\fBThread Queue\fP"
.br
.RI "\fIThread Queue management services\&. \fP"
.ti -1c
.RI "\fBVirtual Timer\fP"
.br
.RI "\fIVirtual Timer management services\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Kernel main interface\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
