.TH "Kernel" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel \- 
.PP
Kernel overview\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBImplementation\fP"
.br
.RI "\fIKernel port independent code implementation\&. \fP"
.ti -1c
.RI "\fBInterface\fP"
.br
.RI "\fIKernel main interface\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Kernel overview\&. 

Main kernel interface is divided into several sections\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
