.TH "portStck" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portStck \- 
.PP
Stack structure used for stack declaration in order to force the alignment Alignment of stack structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kcore\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "portReg_T \fBreg\fP"
.br
.RI "\fIA structure field representing stack data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Stack structure used for stack declaration in order to force the alignment Alignment of stack structure\&. 
.SH "Field Documentation"
.PP 
.SS "portReg_T portStck::reg"

.PP
A structure field representing stack data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
