.TH "portCtx" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portCtx \- 
.PP
Port context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpu\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBportReg_T\fP \fBr0\fP"
.br
.RI "\fIData pushed on stack during context switching\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Port context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBportReg_T\fP portCtx::r0"

.PP
Data pushed on stack during context switching\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
