.TH "profile.h" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
profile.h \- 
.PP
Family port specific configuration options\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.PP
.RI "\fBGeneric family defaults\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBCPU_DEF_SYSTMR_MAX_VAL\fP   0xfful"
.br
.RI "\fISystem timer maximum value\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Family port specific configuration options\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
