.TH "Semaphore" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Semaphore \- 
.PP
Counting semaphore\&.  

.SS "Data types group"
brief description 
.in +1c
.ti -1c
.RI "typedef CFG_SEMAPHORE_CNT_T \fBesSemCnt_T\fP"
.br
.ti -1c
.RI "typedef struct esSem \fBesSem_T\fP"
.br
.ti -1c
.RI "#define \fBCFG_SEMAPHORE_CNT_T\fP   int16_t"
.br
.in -1c
.SS "Function group"
brief description 
.in +1c
.ti -1c
.RI "void \fBesSemInit\fP (esSem_T *sem, esSemCnt_T cnt)"
.br
.RI "\fIInitialize a semaphore\&. \fP"
.ti -1c
.RI "void \fBesSemTerm\fP (esSem_T *sem)"
.br
.ti -1c
.RI "void \fBesSemWait\fP (esSem_T *sem)"
.br
.RI "\fIWait on a semaphore\&. \fP"
.ti -1c
.RI "void \fBesSemWaitTimeout\fP (esSem_T *sem, \fBesTick_T\fP time)"
.br
.RI "\fIWait on a semaphore\&. \fP"
.ti -1c
.RI "void \fBesSemPost\fP (esSem_T *sem)"
.br
.RI "\fIIncrement the value of a semaphore\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Counting semaphore\&. 


.SH "Function Documentation"
.PP 
.SS "void esSemInit (esSem_T *sem, esSemCnt_Tcnt)"

.PP
Initialize a semaphore\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsem\fP Semaphore: points to a semaphore object to initialize\&. 
.br
\fIcnt\fP Count: is an initial value to set the semaphore to\&. 
.RE
.PP

.SS "void esSemWait (esSem_T *sem)"

.PP
Wait on a semaphore\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsem\fP Semaphore: points to a semaphore object to initialize\&. 
.RE
.PP

.SS "void esSemWaitTimeout (esSem_T *sem, \fBesTick_T\fPtime)"

.PP
Wait on a semaphore\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsem\fP Semaphore: points to a semaphore object to initialize\&. 
.br
\fItime\fP Time: the timeout time specified in system ticks\&. 
.RE
.PP

.SS "void esSemPost (esSem_T *sem)"

.PP
Increment the value of a semaphore\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsem\fP Semaphore: points to a semaphore object to initialize\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
