.TH "semaphore.h" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semaphore.h \- 
.PP
Interface of semaphore\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'kernel/kernel\&.h'\fP
.br

.SS "Functions"

.PP
.RI "\fBFunction group\fP"
.br
brief description 
.PP
.in +1c
.in +1c
.ti -1c
.RI "void \fBesSemInit\fP (esSem_T *sem, esSemCnt_T cnt)"
.br
.RI "\fIInitialize a semaphore\&. \fP"
.ti -1c
.RI "void \fBesSemTerm\fP (esSem_T *sem)"
.br
.ti -1c
.RI "void \fBesSemWait\fP (esSem_T *sem)"
.br
.RI "\fIWait on a semaphore\&. \fP"
.ti -1c
.RI "void \fBesSemWaitTimeout\fP (esSem_T *sem, \fBesTick_T\fP time)"
.br
.RI "\fIWait on a semaphore\&. \fP"
.ti -1c
.RI "void \fBesSemPost\fP (esSem_T *sem)"
.br
.RI "\fIIncrement the value of a semaphore\&. \fP"
.in -1c
.in -1c
.SS "Data types group"
brief description 
.in +1c
.ti -1c
.RI "#define \fBCFG_SEMAPHORE_CNT_T\fP   int16_t"
.br
.ti -1c
.RI "typedef CFG_SEMAPHORE_CNT_T \fBesSemCnt_T\fP"
.br
.ti -1c
.RI "typedef struct esSem \fBesSem_T\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface of semaphore\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic
.RE
.PP
Detailed description 
.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
