.TH "Port template" 3 "Tue Oct 29 2013" "Version 1.0BetaR01" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Port template \- 
.PP
Templates\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCPU port configuration\fP"
.br
.RI "\fICPU port specific configuration options\&. \fP"
.ti -1c
.RI "\fBCPU port interface\fP"
.br
.RI "\fICPU port macros and functions\&. \fP"
.ti -1c
.RI "\fBCPU port internals\fP"
.br
.RI "\fICPU port inner work\&. \fP"
.ti -1c
.RI "\fBCompiler port\fP"
.br
.RI "\fICompiler provided macros and data types\&. \fP"
.ti -1c
.RI "\fBDefault Debug configuration\fP"
.br
.RI "\fIDefault Debug Configuration settings\&. \fP"
.ti -1c
.RI "\fBDefault Kernel configuration\fP"
.br
.RI "\fIDefault Kernel Configuration settings\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Templates\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
