.TH "Family port configuration" 3 "Sat Nov 30 2013" "Version 1.0BetaR02" "eSolid - Real-Time Kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Family port configuration \- 
.PP
Family port specific configuration options\&.  

.SS "Generic family defaults"

.in +1c
.ti -1c
.RI "#define \fBCPU_DEF_SYSTMR_MAX_VAL\fP   0xfful"
.br
.RI "\fISystem timer maximum value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Family port specific configuration options\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define CPU_DEF_SYSTMR_MAX_VAL   0xfful"

.PP
System timer maximum value\&. This macro specifies maximum value that can be reloaded into system timer counter\&. For example, if the system timer is an 8-bit counter than this macro would have the value of 0xffu (255)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Real-Time Kernel from the source code\&.
